

[colors]
draw_bold_text_with_bright_colors = false


[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"


[cursor.style]
shape = "Block"
blinking = "Always"


[env]
TERM = "xterm-256color"

# [font]
# size = 18
# # use_thin_strokes = true

[font]
size = 16.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 100000

[window]
startup_mode = "Maximized"
dynamic_title = true
title = "Terminal"
opacity = 0.99

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# decorations = "buttonless"

